### ISSUE TITLE
碰见一个用你工具失效的软件

### ISSUE THREAD

**Issue by cqpsjsl** [newdive/uzmap-resource-extractor#1]
https://www.lanzous.com/ib7krqb

**Comment by newdive** [comment]
嗯，这个是由于key值提取出错导致，目前已经修复 。[(详情见提交记录)](https://github.com/newdive/uzmap-resource-extractor/commit/111d188f3e4eaf9eec53f220702c134a26a025fb)
PS:  抱歉今天下午才看到 （最近忙一直没上github）。 
      后续有问题欢迎继续提出。
