### ISSUE TITLE
大佬，新版有办法

### ISSUE THREAD

**Issue by zyzzmd** [newdive/uzmap-resource-extractor#11]
运行新版没有config.xml文件

**Comment by newdive** [comment]
把样例发过来，我找时间看下 @zyzzmd

**Comment by zyzzmd** [comment]
好的 样本链接: https://wwn.lanzoul.com/iGa64008x4hi 密码:64ja

**Comment by newdive** [comment]
这个样例是dcloud的
这个项目是解密apicloud的，
两个是不同的框架，你看清楚了再发
