### ISSUE TITLE
key似乎读取失败了，提取成功，但文件依旧不可读

### ISSUE THREAD

**Issue by BloveDawn** [newdive/uzmap-resource-extractor#14]
## 问题

提取成功，但文件依旧不可读

> 输出

```shell
python main.py sxxqt_110133.apk
/home/Projects/uzmap-resource-extractor/sxxqt_110133
completeddecrypt assets/widget/script/jsQR.js.min.jsin.jss.jsll.htmllmlhtml
耗时 : 1.7752563953399658 秒
```

## 下载链接
[lanzou-sxxqt_110133](https://bluedawn.lanzouu.com/i6oNN03o5rvg)

**Comment by BloveDawn** [comment]
## 版本信息输出如下

```text
python main.py -v sxxqt_110133.apk
共找到 0 个 apicloud apk
```

**Comment by BloveDawn** [comment]
![图片](https://user-images.githubusercontent.com/40706446/164970909-0ddf769e-d55a-4d48-92e8-38a2ea5a2f29.png)
上图是调试结果，`uz_version`被读取为`uz_vers`

**Comment by BloveDawn** [comment]
我通过临时改变`uz_version`为`uz_vers`解决了这个问题，读取成功，解密成功。

**Comment by newdive** [comment]
apk_util.py 中对AndroidManifest.xml中字符串常量的解析有误，导致最后一个字符串不能完整读取
而这个样本中 uz_version属性刚好是最后一个字符串，所以导致了无法正确读取apk信息
问题已经修复 @BloveDawn
