### ISSUE TITLE
可以通过pyinstaller打包成exe可执行文件嘛

### ISSUE THREAD

**Issue by LeXiangNet** [newdive/uzmap-resource-extractor#17]
可以通过pyinstaller打包成exe可执行文件嘛？就是不用通过执行python main.py xx.apk这个cmd语句去执行解密过程，而是把项目打包成exe可执行文件，直接输入xx.apk就可以执行解密过程

**Comment by newdive** [comment]
打包应该没问题，但个人感觉意义不大，而且与这个项目关联不大
需要注意emulator分支里边有unicorn的依赖 ， 这个打包不知道会不会有其它问题，没试过
另外两个分支只依赖 pycryptodome 包， 打包应该没多大问题

**Comment by LeXiangNet** [comment]
我这边尝试打包后 到执行if not msgQueue:
            msgQueue = multiprocessing.Manager().Queue(0)就不执行了 就开始重复运行main.py

**Comment by newdive** [comment]
这个 multiprocessing包 的打包问题，
你自行搜索下相关的解决方法就好了，
pyinstaller 或者 nuitka 都有相应的解决方法的

**Comment by LeXiangNet** [comment]
好的 我先去百度一下

**Comment by LeXiangNet** [comment]
非常感谢这么及时的解决我的问题 辛苦
