### ISSUE TITLE
大佬有AndroidNativeEmu 方式的文章吗，我发现用你resources 里面提供的解密出来的文件（20220426_issue14.apk），都是0kb，信息如下，改如何解决

### ISSUE THREAD

**Issue by acalldelay** [newdive/uzmap-resource-extractor#18]
Register native ('bs', '(Ljava/lang/String;I)Ljava/lang/String;') failed on class Enslecb.
Register native ('bbs', '([BI)Ljava/lang/String;') failed on class Enslecb.
Register native ('md', '(Ljava/lang/String;I)Ljava/lang/String;') failed on class Enslecb.
Register native ('bmd', '([BI)Ljava/lang/String;') failed on class Enslecb.
Register native ('pm', '(Ljava/lang/Object;)Ljava/lang/String;') failed on class Enslecb.
Register native ('km', '(Ljava/lang/Object;)Ljava/lang/String;') failed on class Enslecb.

**Comment by newdive** [comment]
1、你给的这些提示是由于我这个类没有实现这些方法，所以androidnativeemu会给出这些警告
而实际这些方法与我们的解密无关，可用可不用，你可以自己补全后就不会告警
2、我自己测试过 python2 、python3.6、 python3.7 的都是正常解密的，
你得详细说明下你使用的方式以及使用的环境
@acalldelay

**Comment by acalldelay** [comment]
我使用的的python3.7的环境

**Comment by acalldelay** [comment]
我使用的是python3.7的命令。命令如下python main.py -o F:\workspace\github\uzmap-resource-extractor\decode1 -e  20201203.apk ，20201203.apk这个apk是从你resources文件中哪里出来测试的，运行后，输出目录里面的所有文件都是0kb

**Comment by acalldelay** [comment]
我主要是测试AndroidNativeEmu这个方式。另外一种方式是可以正常获取到的。只是我想了解下AndroidNativeEmu这种方式

**Comment by newdive** [comment]
> 我使用的是python3.7的命令。命令如下python main.py -o F:\workspace\github\uzmap-resource-extractor\decode1 -e 20201203.apk ，20201203.apk这个apk是从你resources文件中哪里出来测试的，运行后，输出目录里面的所有文件都是0kb

测试正常 估计是与你本地环境有关
如果盘不可写或者磁盘空间不足也是无法解密的，运行过程中应该会有报错输出的
请把你具体的运行环境参数说明下
另外可以先测试下不指定 `-o` 参数能否正常输出解密文件 @acalldelay

**Comment by newdive** [comment]
> 我主要是测试AndroidNativeEmu这个方式。另外一种方式是可以正常获取到的。只是我想了解下AndroidNativeEmu这种方式

使用方式可以参考 [emu_support/uzm_emu.py](https://github.com/newdive/uzmap-resource-extractor/blob/emu_support/emu_support/uzm_emu.py) 文件中的方法自己进行运行调试
项目中的代码判断apk中使用rc4加密资源文件后，会直接调用numpy进行异或操作，没有通过AndroidNativeEmu 调用 `ohs` 方法，(出于运行效率的考虑)
如果要通过AndroidNativeEmu 调用实际的解密方法可以参考下边代码 
```
apkFilePath = 你的apk路径
#解析并创建 UZMEmuContext
appInfo, signatureBytes, soContent = uzm_emu_util.readInfoForEmuFromApk(apkFilePath)
appName = appInfo['package']
ctx = uzm_emu.UZMEmuContext(appName, signatureBytes, soContent)
#读取并解密文件
asssetFilePath = 你要解密的资源文件路径
decryptAssetBytes = None
with open(asssetFilePath , 'rb' ) as f:
    assetBytes = f.read()
    decryptAssetBytes  = uzm_emu.decryptFromCtx(ctx, assetBytes )
# decryptAssetBytes  就是解密后的字节
```

**Comment by acalldelay** [comment]
在uzm_emu.py的decryptFromCtx函数中 执行  ohsResult = uzmCtx.jniInterface.ohs(uzmCtx.emulator, encBytes, 0) ，返回的值的空的

**Comment by acalldelay** [comment]
jniInterface.ohs 这个接口是apicloud解密的接口吗，，从什么地方可以获取到这个接口的干嘛用的

**Comment by newdive** [comment]
> jniInterface.ohs 这个接口是apicloud解密的接口吗，，从什么地方可以获取到这个接口的干嘛用的

你先了解下apicloud是如何解密的再来用吧，不然没法和你高效的进行沟通

**Comment by acalldelay** [comment]
我从这个文章。大致了解了。。http://www.javashuo.com/article/p-sbdpacma-sd.html，那理论上。我把加密的byte串通过jniInterface.ohs(uzmCtx.emulator, encBytes, 0)调用，返回值就应该是解密的，可是我返回来的是0，导致这里不好验证

**Comment by newdive** [comment]
> 我从这个文章。大致了解了。。[http://www.javashuo.com/article/p-sbdpacma-sd.html，那理论上。我把加密的byte串通过jniInterface.ohs(uzmCtx.emulator](http://www.javashuo.com/article/p-sbdpacma-sd.html%EF%BC%8C%E9%82%A3%E7%90%86%E8%AE%BA%E4%B8%8A%E3%80%82%E6%88%91%E6%8A%8A%E5%8A%A0%E5%AF%86%E7%9A%84byte%E4%B8%B2%E9%80%9A%E8%BF%87jniInterface.ohs(uzmCtx.emulator), encBytes, 0)调用，返回值就应该是解密的，可是我返回来的是0，导致这里不好验证

1、我之前说的 ，我不知道你本地环境配置到底是怎样的，你自己不说明，没法帮你定位具体问题
2、我给你的样例代码里边没有  `uzmCtx.jniInterface.ohs(uzmCtx.emulator, encBytes, 0) `， 不知道你有没有按我的思路去测试。 这样也没法给你准确的思路
只能给你点提示，你自己如果要调试验证先看好代码后再做
（PS 有问题也想好了写仔细了，这里不是即时聊天）

-     在调用 jniInterface.ohs 方法之前需要做 jniInterface的初始化
      如调用  JNI_Onload 方法（这里会加入apk签名的校验），这样才能确保后续方法能准确调用
      返回空 估计你没按照我写的样例测试，没有加入签名验证导致的

**Comment by acalldelay** [comment]
环境 ：
win10 64位
python3.7.0 64位

流程
1、拉取git
2、切换到emu_support分支
3、子模块更新（AndroidNativeEmu 最新版本2021-2-20）
4、pip install -r requirements.txt
   pip install -r optional-requirements.txt
5、进入AndroidNativeEmu目录
   pip install -r requirements.txt
   
   
测试样例：
def test():
    apkFilePath = r'F:\workspace\github\uzmap-resource-extractor\20201203.apk'
    #解析并创建 UZMEmuContext
    appInfo, signatureBytes, soContent = uzm_emu_util.readInfoForEmuFromApk(apkFilePath)
    appName = appInfo['package']
    ctx = uzm_emu.UZMEmuContext(appName, signatureBytes, soContent)
    #读取并解密文件
    asssetFilePath = r'F:\workspace\github\uzmap-resource-extractor\config.xml'
    decryptAssetBytes = None
    with open(asssetFilePath , 'rb' ) as f:
        assetBytes = f.read()
        decryptAssetBytes  = uzm_emu.decryptFromCtx(ctx, assetBytes )
        print(decryptAssetBytes) #返回空数据
		
		
我根据uzm_emu.decryptFromCtx跟踪进去
def decryptFromCtx(uzmCtx, encBytes):
    with uzmCtx:#这里会调用__enter__函数执行 
        if isinstance(encBytes, bytes):
            encBytes = bytearray(encBytes)
        if not encBytes:
            return b''  # return empty bytes
        ohsResult = uzmCtx.jniInterface.ohs(uzmCtx.emulator, encBytes, 0)#执行完这个，返回0
        return bytes(ohsResult)
		
大致流程就是上面这样

**Comment by newdive** [comment]
发下运行过程的日志记录
还有顺便打印下 `appInfo,` `signatureBytes` `assetBytes `  这几个变量
如果是字节的用base64转下
如果量太大存到文件再发上来

**Comment by acalldelay** [comment]
[运行记录.txt](https://github.com/newdive/uzmap-resource-extractor/files/9101733/default.txt)

运行代码：
def test():
    apkFilePath = r'F:\workspace\github\uzmap-resource-extractor\20201203.apk'
    #解析并创建 UZMEmuContext
    appInfo, signatureBytes, soContent = uzm_emu_util.readInfoForEmuFromApk(apkFilePath)
    print("appInfo:")
    print(appInfo)
    print("signatureBytes:")
    print(base64.b64encode(signatureBytes))
    print("soContent:")
    print(base64.b64encode(soContent))
    appName = appInfo['package']
    ctx = uzm_emu.UZMEmuContext(appName, signatureBytes, soContent)
    #读取并解密文件
    asssetFilePath = r'F:\workspace\github\uzmap-resource-extractor\config.xml'
    decryptAssetBytes = None
    with open(asssetFilePath , 'rb' ) as f:
        assetBytes = f.read()
        print("assetBytes:")
        print(base64.b64encode(assetBytes))
        decryptAssetBytes  = uzm_emu.decryptFromCtx(ctx, assetBytes )
        print("decryptAssetBytes:")
        print(decryptAssetBytes) #返回空数据
    # decryptAssetBytes  就是解密后的字节

if __name__ == '__main__':
   # main()
   test()
   print('over')

**Comment by newdive** [comment]
你那边识别的签名字节是错误的，导致JNI_Onload 的时候校验不通过，后续调用方法无法返回正常参数
正确的签名字节如下：
`
MIICizCCAfSgAwIBAgIEVtuWXjANBgkqhkiG9w0BAQUFADCBiDENMAsGA1UEBhMEKHpoKTESMBAGA1UECBMJKEJlaWppbmcpMRIwEAYDVQQHEwkoQmVpamluZykxGTAXBgNVBAoMEChjZnoyNjAwQHFxLmNvbSkxGTAXBgNVBAsMEChjZnoyNjAwQHFxLmNvbSkxGTAXBgNVBAMMEChjZnoyNjAwQHFxLmNvbSkwIBcNMTYwMzA2MDIzMDU0WhgPMjExNjAyMTEwMjMwNTRaMIGIMQ0wCwYDVQQGEwQoemgpMRIwEAYDVQQIEwkoQmVpamluZykxEjAQBgNVBAcTCShCZWlqaW5nKTEZMBcGA1UECgwQKGNmejI2MDBAcXEuY29tKTEZMBcGA1UECwwQKGNmejI2MDBAcXEuY29tKTEZMBcGA1UEAwwQKGNmejI2MDBAcXEuY29tKTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA0nhkLyCL9Q6NS3lNGcl5T2t7M4frAVNKAnyWVKN/Pw8jTQbr+Sz0ZtXmDwP0iLbvqffAxgxm/RxLLhmCR4G+uxX6hRRjg/2B0ePzwbQMus/RqlKNW8qLpy4DmoZSQi5idVc58G6XhoJGCs2loRxg9JqW9AEi+ukDf9iuBSB9Rh0CAwEAATANBgkqhkiG9w0BAQUFAAOBgQBOnTyzsoXXEaYFdNMdOhr3LGwDTtMejXPOjFmZhSw8wvWWlJpNQEomwF4ZN/nxrH/jwraA70j7irSqgnTMgQfgHQPxo5mDxXu+6Y2Q00IimZPYRqgMNzxPa3S2WsDPyy5yxtV67tOYSOqeJORqrzaoM9kNILH3nfGO2Gfh46q8sw==
`

你参考下  `uzm_emu_util.readInfoForEmuFromApk`  方法， 
跟踪下 `signatureBytesArr`的值，自己比对下

另外我本地的 asn1crypto 的版本是 0.24.0
你看下你本地的版本是多少，可能有关联

**Comment by acalldelay** [comment]
谢谢大佬。这个问题解决了。是环境问题
我安装环境的asn1crypto 这个是1.5.1的 会导致签名不对
我降级到asn1crypto==0.24.0就可以了

**Comment by newdive** [comment]
修改asn1crypto 获取证书内容的方式， 保证大于1.0.0版本可以获取正确的apk签名字节
具体参考[提交记录 ](https://github.com/newdive/uzmap-resource-extractor/commit/cdc2ffdeadd26c0da6e3b05f28834fbd4e4fd27a) @acalldelay
