### ISSUE TITLE
hello,在翻遍各类博文后找到该静态提取资源工具,很方便

### ISSUE THREAD

**Issue by bushuaigege** [newdive/uzmap-resource-extractor#19]
#### 之后肯定有合作需要想直接和你建立联系,因为我是服务端技术,对逆向不熟悉,通过xpose/arm ultra/magisk等各种确实很麻烦也一直没解决我我的问题,所以想咖啡赞助,感谢你的开源(虽然现在开源很正常)但找到你并完成解密真的解决很大一个困难;   期待你的回信: bushuaigege@sina.cn

**Comment by newdive** [comment]
庆幸项目能对你有所帮助！
不过本项目没有接受赞助的目的，只是业余时间维护；加之最近在忙其它事，所以这方面的时间投入会比较少。
不过还是谢谢你的好意！

**Comment by bushuaigege** [comment]
希望能在以后有合作方便联系,可以留下邮箱嘛?




-----------------------------------------------------------
专注  协作  激情  适应
 
发件人： SamLee
发送时间： 2022-10-15 11:59
收件人： newdive/uzmap-resource-extractor
抄送： Buke; Author
主题： Re: [newdive/uzmap-resource-extractor] hello,在翻遍各类博文后找到该静态提取资源工具,很方便 (Issue #19)
庆幸项目能对你有所帮助！
不过本项目没有接受赞助的目的，只是业余时间维护；加之最近在忙其它事，所以这方面的时间投入会比较少。
不过还是谢谢你的好意！
