### ISSUE TITLE
可以提供一个加密的吗

### ISSUE THREAD

**Issue by okeyzero** [newdive/uzmap-resource-extractor#6]
希望能写一个加密文件的功能     因为我研究的时候 修改文件之后 替换回去 这样更方便调试   解密后的替换进去 发现不能正常运行app

**Comment by newdive** [comment]
你好 你说的解密后修改再替换的话会涉及到app的重新打包 ，这个不是简单的直接加密替换旧ok的了 ，而且你提的这个功能并不属于这个项目的开发的目的。

另外针对你说的加密，可以给你一些实现建议：这里的加密是rc4加密，你可以直接利用提取的密钥和加密库中的rc4算法再重新加密一次就ok的了。
