### ISSUE TITLE
测试某些app的时候会卡死

### ISSUE THREAD

**Issue by junanliuwei** [newdive/uzmap-resource-extractor#7]
python main.py -v /disk1t/samba/apps/api/
...........
error extracting apicloud info :/disk1t/samba/apps/api/讯飞听见_2.0.1428.apk
Traceback (most recent call last):
  File "/disk1t/samba/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
    attrsList = extractManifestAttributes(mBytes)
  File "/disk1t/samba/uzmap-resource-extractor-master/apk_util.py", line 249, in extractManifestAttributes
    stringList = extractStringList(fileBytes,8)
  File "/disk1t/samba/uzmap-resource-extractor-master/apk_util.py", line 228, in extractStringList
    length = (val << 8) | struct.unpack('=b',rawStringDataBlock[offset+1 : offset+2] )
TypeError: unsupported operand type(s) for |: 'int' and 'tuple'
error extracting apicloud info :/disk1t/samba/apps/api/讯飞听见1.0.1038.apk .apk
Traceback (most recent call last):
  File "/disk1t/samba/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
    attrsList = extractManifestAttributes(mBytes)
  File "/disk1t/samba/uzmap-resource-extractor-master/apk_util.py", line 249, in extractManifestAttributes
    stringList = extractStringList(fileBytes,8)
  File "/disk1t/samba/uzmap-resource-extractor-master/apk_util.py", line 228, in extractStringList
    length = (val << 8) | struct.unpack('=b',rawStringDataBlock[offset+1 : offset+2] )
TypeError: unsupported operand type(s) for |: 'int' and 'tuple'
error extracting apicloud info :/disk1t/samba/apps/api/美达罗捷_2.1.3.apk
Traceback (most recent call last):
  File "/disk1t/samba/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
    attrsList = extractManifestAttributes(mBytes)
  File "/disk1t/samba/uzmap-resource-extractor-master/apk_util.py", line 249, in extractManifestAttributes
    stringList = extractStringList(fileBytes,8)
  File "/disk1t/samba/uzmap-resource-extractor-master/apk_util.py", line 228, in extractStringList
    length = (val << 8) | struct.unpack('=b',rawStringDataBlock[offset+1 : offset+2] )
TypeError: unsupported operand type(s) for |: 'int' and 'tuple'

**Comment by newdive** [comment]
你好 可以附带下apk的原件吗 方便这边验证测试。

**Comment by newdive** [comment]
从你给的堆栈报错看， 这个应该是在解析带有utf8编码字符串的apk时候报的错误。
导致报错的原因是对 struct.unpack 方法取值的错误。
这边目前没找到符合要求的apk样本  你可以先在你本地自己测试下。

**Comment by junanliuwei** [comment]
Hi,没想到这么快收到您的回复.


# python main.py -v /disk1t/samba/liuwei/apps
error extracting apicloud info :/disk1t/samba/liuwei/apps/书链_3.5.9.apk7.apk
Traceback (most recent call last):
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
&nbsp; &nbsp; attrsList = extractManifestAttributes(mBytes)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 249, in extractManifestAttributes
&nbsp; &nbsp; stringList = extractStringList(fileBytes,8)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 228, in extractStringList
&nbsp; &nbsp; length = (val << 8) | struct.unpack('=b',rawStringDataBlock[offset+1 : offset+2] )
TypeError: unsupported operand type(s) for |: 'int' and 'tuple'
error extracting apicloud info :/disk1t/samba/liuwei/apps/讯飞听见_2.0.1428.apk67.apkpk
Traceback (most recent call last):
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
&nbsp; &nbsp; attrsList = extractManifestAttributes(mBytes)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 249, in extractManifestAttributes
&nbsp; &nbsp; stringList = extractStringList(fileBytes,8)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 228, in extractStringList
&nbsp; &nbsp; length = (val << 8) | struct.unpack('=b',rawStringDataBlock[offset+1 : offset+2] )
TypeError: unsupported operand type(s) for |: 'int' and 'tuple'
error extracting apicloud info :/disk1t/samba/liuwei/apps/讯飞语记_4.1.1176.apk
Traceback (most recent call last):
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
&nbsp; &nbsp; attrsList = extractManifestAttributes(mBytes)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 249, in extractManifestAttributes
&nbsp; &nbsp; stringList = extractStringList(fileBytes,8)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 228, in extractStringList
&nbsp; &nbsp; length = (val << 8) | struct.unpack('=b',rawStringDataBlock[offset+1 : offset+2] )
TypeError: unsupported operand type(s) for |: 'int' and 'tuple'
error extracting apicloud info :/disk1t/samba/liuwei/apps/红枣FM_2.7.5.apk088.systagpk
Traceback (most recent call last):
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
&nbsp; &nbsp; attrsList = extractManifestAttributes(mBytes)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 249, in extractManifestAttributes
&nbsp; &nbsp; stringList = extractStringList(fileBytes,8)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 228, in extractStringList
&nbsp; &nbsp; length = (val << 8) | struct.unpack('=b',rawStringDataBlock[offset+1 : offset+2] )
TypeError: unsupported operand type(s) for |: 'int' and 'tuple'
error extracting apicloud info :/disk1t/samba/liuwei/apps/讯飞听见1.0.1038.apk274410.apk
Traceback (most recent call last):
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
&nbsp; &nbsp; attrsList = extractManifestAttributes(mBytes)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 249, in extractManifestAttributes
&nbsp; &nbsp; stringList = extractStringList(fileBytes,8)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 228, in extractStringList
&nbsp; &nbsp; length = (val << 8) | struct.unpack('=b',rawStringDataBlock[offset+1 : offset+2] )
TypeError: unsupported operand type(s) for |: 'int' and 'tuple'



上面这些只是报错,一般不会卡死,但是经常到某个app就不走了.需要把那个app删除才可以继续,单独解那个app则没有问题.
&nbsp;
error extracting apicloud info :/disk1t/samba/liuwei/apps/美团外卖_7.28.3.apk7.apk
Traceback (most recent call last):
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
&nbsp; &nbsp; attrsList = extractManifestAttributes(mBytes)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 279, in extractManifestAttributes
&nbsp; &nbsp; attrs = {attrs['name']:attrs['value']}
KeyError: 'name'
error extracting apicloud info :/disk1t/samba/liuwei/apps/美团_10.4.203.apkpk08238058.apk
Traceback (most recent call last):
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 296, in extractAPICloudInfo
&nbsp; &nbsp; attrsList = extractManifestAttributes(mBytes)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/apk_util.py", line 279, in extractManifestAttributes
&nbsp; &nbsp; attrs = {attrs['name']:attrs['value']}
KeyError: 'name'
5631/5633&nbsp; =&gt; /disk1t/samba/liuwei/apps/src/大马力车太保_3.12.20/assets/widget/html/e_ureq_list_frm.htmltml.jst.jsjsoter.jsnt.jssjsil.jsjscssl



到上面这一条卡死了,但是大部分时候都能运行过去.原因不明.按CTRL+C中断之后显示:


^CTraceback (most recent call last):pps/src/大马力车太保_3.12.20/assets/widget/html/e_ureq_list_frm.htmltml.jst.jsjsoter.jsnt.jssjsil.jsjscssl
&nbsp; File "main.py", line 37, in <module&gt;
&nbsp; &nbsp; apkInfos = tools.extractAPICloudApkInfos(args[0],True)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/tools.py", line 126, in extractAPICloudApkInfos
Process ForkPoolWorker-2:
Process ForkPoolWorker-3:
Traceback (most recent call last):
Traceback (most recent call last):
&nbsp; File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
&nbsp; &nbsp; self.run()
&nbsp; File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
&nbsp; &nbsp; self.run()
&nbsp; File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
&nbsp; &nbsp; self._target(*self._args, **self._kwargs)
&nbsp; File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
&nbsp; &nbsp; self._target(*self._args, **self._kwargs)
&nbsp; File "/usr/lib/python3.4/multiprocessing/pool.py", line 108, in worker
&nbsp; &nbsp; task = get()
&nbsp; File "/usr/lib/python3.4/multiprocessing/queues.py", line 355, in get
&nbsp; &nbsp; res = self._reader.recv_bytes()
&nbsp; File "/usr/lib/python3.4/multiprocessing/pool.py", line 108, in worker
&nbsp; &nbsp; task = get()
&nbsp; File "/usr/lib/python3.4/multiprocessing/queues.py", line 354, in get
&nbsp; &nbsp; with self._rlock:
&nbsp; &nbsp; apkInfoMap = _scanAPICloudApks(procPool,msgQueue,resourcePath,True,printLog=printLog)
&nbsp; File "/disk1t/local/data/apicloud/crack/uzmap-resource-extractor-master/tools.py", line 83, in _scanAPICloudApks
&nbsp; File "/usr/lib/python3.4/multiprocessing/synchronize.py", line 96, in __enter__
&nbsp; &nbsp; return self._semlock.__enter__()
&nbsp; File "/usr/lib/python3.4/multiprocessing/connection.py", line 216, in recv_bytes
&nbsp; &nbsp; buf = self._recv_bytes(maxlength)
&nbsp; File "/usr/lib/python3.4/multiprocessing/connection.py", line 416, in _recv_bytes
&nbsp; &nbsp; buf = self._recv(4)
&nbsp; File "/usr/lib/python3.4/multiprocessing/connection.py", line 383, in _recv
&nbsp; &nbsp; chunk = read(handle, remaining)
KeyboardInterrupt
&nbsp; &nbsp; if msgQueue.empty():
&nbsp; File "<string&gt;", line 2, in empty
&nbsp; File "/usr/lib/python3.4/multiprocessing/managers.py", line 731, in _callmethod
&nbsp; &nbsp; conn.send((self._id, methodname, args, kwds))
&nbsp; File "/usr/lib/python3.4/multiprocessing/connection.py", line 206, in send
&nbsp; &nbsp; self._send_bytes(ForkingPickler.dumps(obj))
KeyboardInterrupt
&nbsp; File "/usr/lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
&nbsp; &nbsp; cls(buf, protocol).dump(obj)
&nbsp; File "/usr/lib/python3.4/multiprocessing/reduction.py", line 37, in __init__
&nbsp; &nbsp; def __init__(self, *args):
KeyboardInterrupt




附件发不过去.才2M的都不行



------------------ 原始邮件 ------------------
发件人:&nbsp;"SamLee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年10月3日(星期六) 下午3:11
收件人:&nbsp;"newdive/uzmap-resource-extractor"<uzmap-resource-extractor@noreply.github.com&gt;; 
抄送:&nbsp;"liuwei"<liuwei@chaodao.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题:&nbsp;Re: [newdive/uzmap-resource-extractor] 测试某些app的时候会卡死 (#7)

&nbsp;



 
你好 可以附带下apk的原件吗 方便这边验证测试。

**Comment by newdive** [comment]
你可以发个下载链接

**Comment by newdive** [comment]
卡死的问题我已经修复了 你可以更新下源码试下

**Comment by junanliuwei** [comment]
好的,谢谢 !





那几个出错的app从豌豆荚可以找到历史版本:


https://www.wandoujia.com/apps/6565630/history_v177


https://www.wandoujia.com/apps/6625845/history_v125
&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SamLee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年10月3日(星期六) 下午4:26
收件人:&nbsp;"newdive/uzmap-resource-extractor"<uzmap-resource-extractor@noreply.github.com&gt;; 
抄送:&nbsp;"liuwei"<liuwei@chaodao.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题:&nbsp;Re: [newdive/uzmap-resource-extractor] 测试某些app的时候会卡死 (#7)

&nbsp;



 
卡死的问题我已经修复了 你可以更新下源码试下

**Comment by junanliuwei** [comment]
非常感谢,一次就顺利通过了.
