### ISSUE TITLE
解密失败

### ISSUE THREAD

**Issue by dongny** [newdive/uzmap-resource-extractor#8]
按照说明执行后得到的文件还是加密的，解密失败！
兄弟有空可否帮忙看看，劳驾劳驾！万分感谢！

**Comment by newdive** [comment]
嗯 提供下apk的样本下载链接
还有说明是用什么python版本的  以及运行的os

**Comment by dongny** [comment]
好的，版本号，rc4key都出来了，但解密不行，我的python版本2.7所以用的分支版本。下面是apk下载链接，谢了

http://downloadpkg.apicloud.com/app/download?path=http://7xrkwm.com1.z0.glb.clouddn.com/72a1e8ce33621fa44f6cd14597d7a20_d

**Comment by newdive** [comment]
嗯 这个应该是rc4密钥读取出错了   
 我稍后看下怎么修改吧

**Comment by dongny** [comment]
好的

**Comment by xuan52rock** [comment]
修复好了吗；还有另一个问题就是加固了之后rc4key拿不到

**Comment by newdive** [comment]
> 修复好了吗；还有另一个问题就是加固了之后rc4key拿不到



> 修复好了吗；还有另一个问题就是加固了之后rc4key拿不到

加固后的apk请发对应样本出来

**Comment by newdive** [comment]
> 修复好了吗；还有另一个问题就是加固了之后rc4key拿不到

最近会找时间修复这个bug  , 知道如何改的可以提交pull request

**Comment by newdive** [comment]
@xuan52rock 加固的你得提供下apk的样本  
后续请新开issue ,这个我就先关闭了
